name: Cottontail CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.3
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Test with gradle ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew test --info
      - name: Test with gradle windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew test --info
      - name: ShadowJar
        run: ./gradlew shadowJar